# Generated by Django 5.0.4 on 2024-04-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('logo', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('grandaustralia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rank.grandaustralia')),
                ('grandbahrain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rank.grandbahrain')),
                ('grandjapan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rank.grandjapan')),
            ],
            options={
                'ordering': ('-point',),
            },
        ),
    ]
