# Generated by Django 5.0.4 on 2024-04-25 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=350)),
                ('name', models.CharField(max_length=150)),
                ('birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('bio', models.TextField(max_length=300)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rank.team')),
            ],
        ),
    ]
