# Generated by Django 5.0.4 on 2024-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titles',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
